"""empty message

Revision ID: d6d2a68d3e15
Revises: fa16a62218bf
Create Date: 2021-01-06 09:41:04.324682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d2a68d3e15'
down_revision = 'fa16a62218bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
